//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin()
        {
            this.doctors = new HashSet<doctor>();
        }
    
        public int aid { get; set; }
        public string aname { get; set; }
        public string aphone { get; set; }
        public string aaddress { get; set; }
        public string agender { get; set; }
        public string aemail { get; set; }
        public string apassword { get; set; }
        public string abirth_date { get; set; }
        public string aage { get; set; }
    
        public virtual admin admin1 { get; set; }
        public virtual admin admin2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctor> doctors { get; set; }
    }
}
