//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_donation
    {
        public int blood_donation_id { get; set; }
        public string last_donation { get; set; }
        public string donation_details { get; set; }
        public int pid { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
