//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medi_careEntities2 : DbContext
    {
        public medi_careEntities2()
            : base("name=medi_careEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<blood_donation> blood_donation { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<emergency> emergencies { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<plm_and_slv> plm_and_slv { get; set; }
    }
}
