//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.plm_and_slv = new HashSet<plm_and_slv>();
        }
    
        public int did { get; set; }
        public string dname { get; set; }
        public string dphone { get; set; }
        public string daddresss { get; set; }
        public string dgender { get; set; }
        public string dqualification { get; set; }
        public string dmail { get; set; }
        public string dpassword { get; set; }
        public int aid { get; set; }
        public string dage { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plm_and_slv> plm_and_slv { get; set; }
    }
}
