//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergency
    {
        public int emergencyid { get; set; }
        public string emergency_num1 { get; set; }
        public string emergency_num2 { get; set; }
        public Nullable<int> pid { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
