//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madi_care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.blood_donation = new HashSet<blood_donation>();
            this.emergencies = new HashSet<emergency>();
        }
    
        public int pid { get; set; }
        public string pname { get; set; }
        public string pphone { get; set; }
        public string paddress { get; set; }
        public string page { get; set; }
        public string pblood_group { get; set; }
        public string pgender { get; set; }
        public string pweight { get; set; }
        public string phight { get; set; }
        public string paassword { get; set; }
        public string pbmi { get; set; }
        public string pbmr { get; set; }
        public string pbp { get; set; }
        public string pbirth_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_donation> blood_donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emergency> emergencies { get; set; }
    }
}
